### ISSUE TITLE
POST vs PUT requests for document creation

### ISSUE THREAD

**Issue by theodore-evans** [pqaidevteam/pqai-db#1]
Regarding the (as-yet unimplemented) document creation API endpoints in Readme.md:

|      | Method   | Endpoint                       | Comments                                         |
| ---- | -------- | ------------------------------ | ------------------------------------------------ |
| *    | `POST`   | `/docs/[docId]`                | Add (or overwrite) a new non-patent document     |
| *    | `POST`   | `/docs/[docId]/drawings/[n]`   | Add (or overwrite) a new drawing                 |

I believe that a PUT request is more appropriate for creating/updating an entry directly by specifying its url, rather than POST (idempotency, see https://www.geeksforgeeks.org/diffrence-between-put-and-post-http-requests/#:~:text=PUT%20method%20is%20idempotent.,different%20URIs%20created%20on%20server.)

**Comment by mahesh-maan** [comment]
That makes sense, @theodore-evans. `PUT` is more appropriate here. I've updated the README to reflect this change.
